### ISSUE TITLE
uptimerobot.com

### ISSUE THREAD

**Issue by p1r473** [ShadowWhisperer/BlockLists#150] opened 2024-05-29 02:14 UTC
This is a false positive
its an outage detection service
monitors when your site goes down

**Comment by ShadowWhisperer** [comment] 2024-05-29 02:52
Duplicate of 

https://github.com/ShadowWhisperer/BlockLists/issues/13

**Comment by p1r473** [comment] 2024-05-29 03:25
Whoops, sorry!

**Closed** 2024-05-29 03:25 UTC

**Comment by ShadowWhisperer** [comment] 2024-05-29 13:10
No problem. It didn't show the first time I searched the closed issues for this domain. I had to manually look for it,

**Comment by spirillen** [comment] 2024-05-29 13:38
Yep, by default the search feature is only searching in open issues, you have to change that manually
