### ISSUE TITLE
False positive - reddit.com & google.com

### ISSUE THREAD

**Issue by botflakes** [ShadowWhisperer/BlockLists#163] opened 2024-08-05 02:51 UTC
Literally title. After the last update, reddit.com and google.com are blocked. For whatever reason.

I guess there are more legit sites blocked than just these two

**Comment by Suzano-Sho** [comment] 2024-08-05 03:19
Came here to report the exact same thing. Had to disable the blocklist because Google (and anything related, like YouTube or dns.google) was suddenly being blocked on this list.

**Comment by ShadowWhisperer** [comment] 2024-08-05 03:27
Update again. Had an issue on my end. Fixed it within a couple minutes. Should be fixed.

**Comment by Suzano-Sho** [comment] 2024-08-05 03:34
Just checked, working perfectly again! Thanks!

**Comment by ShadowWhisperer** [comment] 2024-08-05 03:38
Sorry for the inconvenience

**Closed by ShadowWhisperer** 2024-08-05 03:38 UTC

**Comment by spirillen** [comment] 2024-08-05 08:19
This is a open question.. because I don't understand this, like at all... why, it is very contradicted behavior

## Q

You are using anti tracking and privacy aware lists to protect your privacy, right?

> because Google (and anything related, like YouTube or dns.google) was suddenly being blocked

How is it then you all screams like **BLEEP**, when the list actually do as supposed to? Alphabet is along side adobe the biggest spyware, tracking, privacy invasive companies and domains out there. 

So why these contradictions??  My life is very fine by blocking Alphabet, meta, Cloudflare. if people hides there content with those walls of the Closed Garden, well, then it isn't public available and I don't care. There are plenty of information is the public zone.

So please, try to explain this to me

**Comment by Suzano-Sho** [comment] 2024-08-05 12:01
> ## Q
> You are using anti tracking and privacy aware lists to protect your privacy, right?

^I'd say that this assumption is an error on your part.

> How is it then you all screams like **BLEEP**, when the list actually do as supposed to? 

It's very obvious that the behavior we reported is NOT what this list was intended to do. That is why it has been labeled as an error, by the creator.

> My life is very fine by blocking Alphabet, meta, Cloudflare.

That's great, and I'm happy for you. I, on the other hand, have things on my home network that rely on being able to reach out to some of these services. As a network technician by trade, these lists are convenient for me because they help me allow certain logical network segments to connect to what they need to connect to, while still blocking what they don't need on my admittedly complex home network.

**Comment by ShadowWhisperer** [comment] 2024-08-05 13:18
For me, this is used at work.

99.9% of computer that come in for repair, use these services. Some customers wait/watch while I work on it, if it's something simple or they need to show me. If I open Chrome while the owner is watching and it goes straight to a page not found, they are going ask why, or claim that is the problem they were having. I'm not going to take the time to explain why it won't load, and what tracking is, to every single person. If I'm working on the computer have to download drivers, Google is the homepage on 99.9% of them. I don't care if Google knows I searched for "HP EliteBook 8560w drivers". I have a lot of business customers that use Gmail. I'm not going to tell them I don't work on Gmail because of x. They aren't going to care, they just want their email to work.

I've had zero problems with Cloudflare. I've had problems with Quad9 and others not resolving some domains.

Alt DNS is blocked under **Bloat**, and all DNS requests are redirected with iptables.

What I block at home, is not the same as what I block at work.
